In [7]:
            ###차원확장
import numpy as np

a = np.array([[1,2],[3,4]])

expanded = np.expand_dims(a,0)
print(expanded)
print(f"{expanded.shape}\n")
expanded = np.expand_dims(a,1)
print(expanded)
print(f"{expanded.shape}\n")
expanded = np.expand_dims(a,2)
print(expanded)
print(f"{expanded.shape}\n")

[[[1 2]
  [3 4]]]
(1, 2, 2)

[[[1 2]]

 [[3 4]]]
(2, 1, 2)

[[[1]
  [2]]

 [[3]
  [4]]]
(2, 2, 1)



In [10]:
import numpy as np
np_ones = np.ones((1,2,1,3))
print(np_ones)



[[[[1. 1. 1.]]

  [[1. 1. 1.]]]]


In [41]:
a= [1,2,2,3,3,3,4,4]
u_a, indexes, counts  = np.unique(a,return_index=True,return_counts=True) #.unique에 정의된 순서로 출력
print(u_a, counts, indexes)

[1 2 3 4] [1 2 3 2] [0 1 3 6]


In [40]:
a= [1,2,2,3,3,3,4,4]
u_a,  counts, indexes  = np.unique(a,return_counts=True,return_index=True)
print(u_a, indexes, counts)




[1 2 3 4] [1 2 3 2] [0 1 3 6]


In [43]:
def add(a=1, b=1):
    return a,b, a+b     #정의된 순서되로 출력!!!!!!

sum, a, b= add(2,3)
print(a,b,sum)

3 5 2


In [49]:
a = np.array([1,4,2,3])
b=np.sort(a)        #b=a[np.argsort(a)]
print(f"a {a}")     #print(f"a_1 {a_1}")
print(f"b {b}")
c= np.argsort(a)
print(f"c {c}")
print(f"c {a[c]}")
a[c.sort()]     #argsort 하면 원본으로 롤백 가능
print(f"a {a}")

a [1 4 2 3]
b [1 2 3 4]
c [0 2 3 1]
c [1 2 3 4]
a [1 4 2 3]
