In [2]:
import numpy as np
x = np.arange(15, dtype=np.int64).reshape(3, 5)
x[1:, ::2] = -99
print(x)

[[  0   1   2   3   4]
 [-99   6 -99   8 -99]
 [-99  11 -99  13 -99]]


In [5]:
a= np.sort(x, axis=0)
print(a)


[[-99   1 -99   3 -99]
 [-99   6 -99   8 -99]
 [  0  11   2  13   4]]


In [8]:
a= np.sort(x, axis=1)
print(a)

[[  0   1   2   3   4]
 [-99 -99 -99   6   8]
 [-99 -99 -99  11  13]]


In [74]:
x=np.arange(15, dtype=np.int64).reshape(3,5)
x[1:, ::2] = -99
print(f"x{x}")

print(f"#1\n최대{np.max(x[:,0])}\n최소{np.min(x[:,0])}\n평균{np.mean(x[:,0])}")
print(f"#2 : {np.sum(x[1,:])}")
a=np.array([1,1,2,3,4,5,5,5,5,7,8,9,10,11,24,100])
b3=np.argsort(a)
print(f"#3\n{a[b3[::-1]]}")

x[[  0   1   2   3   4]
 [-99   6 -99   8 -99]
 [-99  11 -99  13 -99]]
#1
최대0
최소-99
평균-66.0
#2 : -283
#3
[100  24  11  10   9   8   7   5   5   5   5   4   3   2   1   1]


x[[  0   1   2   3   4]
 [-99   6 -99   8 -99]
 [-99  11 -99  13 -99]]
#1
최대0
최소-99
평균-66.0
[-99   6 -99   8 -99]
#2 : -283
