In [5]:
import numpy as np
x= np.array([3,1,2,"a"])
print(x)
print([3,1,2,"e"])
print(type(x))
print(type((3,1,2)))

['3' '1' '2' 'a']
[3, 1, 2, 'e']
<class 'numpy.ndarray'>
<class 'tuple'>


In [13]:
c=[[1],[1,2]]
d= np.array(([1,1],[1,2]))
for x,y in d:
    print(x,y)

1 1
1 2


In [14]:
%ls

 C ����̺��� �������� �̸��� �����ϴ�.
 ���� �Ϸ� ��ȣ: B208-3F54

 c:\Users\gksdydcks\Documents\python\test12 ���͸�

2024-12-13  ���� 12:17    <DIR>          .
2024-12-13  ���� 12:17    <DIR>          ..
2024-12-13  ���� 10:33             1,653 12_13_1.py
2024-12-13  ���� 12:17                 0 12_13_5.ipynb
2024-12-13  ���� 11:41               858 12-13_2.py
2024-12-13  ���� 12:02               896 12-13_3.ipynb
2024-12-13  ���� 12:08             1,196 12-13_4.ipynb
               5�� ����               4,603 ����Ʈ
               2�� ���͸�  55,365,804,032 ����Ʈ ����


In [16]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [19]:
x= np. array([1.0,2.0,3.0])
y= np. array([2.0,4.0,6.0])

print(x+y)
print(x-y)
print(x*y)
print(x/y)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [24]:
print(x.shape)
print(x.dtype)
print(d.shape)
print(y/2.0)

(3,)
float64
(2, 2)
[1. 2. 3.]


In [25]:
ndarray6 = np.array([[1,2,3],[4,5,6]])  #2행3열 #2차원
ndarray6.ndim       

2

In [27]:
a=np.array([[1,2],[3,4],[5,6]])
print(a.ndim)       #2차원
print(a.shape)  #3행 2열

2
(3, 2)


In [32]:
a=np.array([[[1],[2]],[[3],[4]],[[5],[6]]])#[]색 개수로 차원 구분가능
print(a.ndim)       #3차원
print(a.shape)

3
(3, 2, 1)


In [33]:
a=np.array([[[1,2],[2,2]],[[3,2],[4,2]],[[5,2],[6,2]]]) 
print(a.ndim)       #3차원
print(a.shape)

3
(3, 2, 2)


In [35]:
np.dot(1,2)

2

In [36]:
ndar1=np.array([3,2])
ndar2=np.array([4,6])
np.dot(ndar1, ndar2)

24

In [38]:
ndar1=np.array([[1,2],[3,4]])
ndar2=np.array([[1,2],[3,4]])
np.dot(ndar1, ndar2)

array([[ 7, 10],
       [15, 22]])

In [42]:
ndar1=np.array([[1,2]])      #!!!앞 행렬의 !열!의 개수 뒤 행렬의 !행!의 개수 같아야함!!!!
ndar2=np.array([[1,2],[3,4]])
np.matmul(ndar1,ndar2)

array([[ 7, 10]])

In [46]:
ndar2 = np.array([[[1],[2]],[[3],[4]]])
print(ndar2.shape)
print(ndar2.ndim)
a = ndar2.flatten()     ##!!행렬 평탄화
print(a.ndim)
print(ndar2)

(2, 2, 1)
3
1
[[[1]
  [2]]

 [[3]
  [4]]]


In [47]:
ndarr = np.array([[1,2],[2,3],[3,4]])
ndarr.reshape(2,3)                       #1차원으로 만든후 다시 재생성

array([[1, 2, 2],
       [3, 3, 4]])

In [49]:
ndarr.reshape(6,1)

array([[1],
       [2],
       [2],
       [3],
       [3],
       [4]])

In [50]:
ndarr.reshape(1,6)

array([[1, 2, 2, 3, 3, 4]])

In [54]:
np.random.randint(5, size=(2,4))

array([[3, 1, 4, 1],
       [3, 2, 1, 3]])

In [52]:
np.random.rand(2,4)

array([[0.62959358, 0.25246362, 0.22378782, 0.79196126],
       [0.07418841, 0.56557289, 0.62034921, 0.68765565]])

In [58]:
rng =np.random.default_rng()
rng.random()

0.7693099892713067

In [62]:
rng.integers(0,10,(2,4))


array([[6, 8, 2, 3],
       [8, 9, 5, 3]], dtype=int64)

In [64]:
ndarr = np.array([[6,3],[5,2],[4,1]])
ndarr >4


array([[ True, False],
       [ True, False],
       [False, False]])

In [67]:
ndarr[ndarr > 1]            #조건식!!특정값 출력

array([6, 3, 5, 2, 4])

In [69]:
ndarr[1:]

array([[5, 2],
       [4, 1]])

In [68]:
ndarr = np.array([[6,3],[5,2],[4,1]])
ndarr[ndarr >4]

array([6, 5])